# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Continuous Integration

on:
  push:
    tags:
      - '*'
    branches:
      - main

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:

  ###################################################
  # Build
  ###################################################

  publish:
    name: Build
    if: "!contains(github.event.head_commit.message, 'skip-ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4

      - name: Publish
        shell: bash
        run: |
          dotnet nuget locals http-cache --clear
          dotnet tool restore
          dotnet cake --target="Publish" \
            --nuget-key="${{secrets.NUGET_API_KEY}}"